language: java
jdk: oraclejdk8
services: redis-server
script: env
addons:
  postgresql: '9.4'
before_install: source ./.envrc
before_script: psql -f prepare-db.sql -U postgres
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: bgrohbiel@pivotal.io
  password:
    secure: "E2VaMGZjEGlfUw/22dxY97tEwQC47kyi5j3BLMZxtKtbTVpi3mUO7JQykXQkN8sGncSS9kylHmkUPgc2rUHdrdoz01oJMOrV6RGRZV6K6Pm5SGvKFiZyVEHSWI03wRrKC+S5gehwW7+3Gl1D5drFS+FX3oLwO1c7eiqcxRoJeUrOHIUXhCgu7KiENIHgSQ7mH5iMFi0jlp8woi5szLedzNdCLQkWz4HA95dfL4ZJwiJwj2tR1coRtICkJrrcQJojS4p5jCWkY6c4L6r6xqDR2fxAW4EuOBLPIy3WIcv7d2NyeXISu+TKl8t7eoxXms+Bstg7jsUyyyj1lwF8xYxJ8z0iSlnXN8PguoQtMnpWWrgpm4hpYX8I5+6AfI4+HGRI8Mk30Qggo8W93KQ+WYjZfFwKNs37Oz9NUNS8rOAnrvfaRjBsoP/NrW7z04cFNxMkucvCIAVm5u8XXWWuCmSMAhUn+weIXvn3THzUnLwA4ryTy+V7jUVcI0YX6oRkfM2fEl3BXK9ytDZY+lpUKdEzAsU5od6CykOkG36PuM46C4GseBpgFASXfTJFjJHeujgnhJBipYg5KHijdD0d1HOP0kOQ+Oelk9aRz1gbfctGaQycvpkGOL+v7nhNQfN1Zd7rg06exq6LflUWdcxsGQqSVC96g56N0zvl3lBaUbdNeRk="
  organization: bgrohbiel
  space: development
  on:
    repo: bengro/url-shortener
