language: java
jdk: oraclejdk8
services: redis-server
script: env
addons:
  postgresql: '9.4'
before_install: source ./.envrc
before_script: psql -f prepare-db.sql -U postgres
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: bgrohbiel@pivotal.io
  password:
    secure: DpR9Pvt6ArGBmx3Ayb8ASL3snMPPPSIXCEUnleWv2IkKbML8rfbeRRhdUuDcPsVfbV0liDbxYRIFMs7M+DbMD5R+DeAZJ7+4+3kjAw1y2wNpsx6xNIsQ19/97IAxtoO27hweHUdAjImdcnUWbcAErvhmp3yTcNr7TkJcdxoAT6BKh2Tg6CAor5wJ66sDos+grRjHWZ9oevJUGIuFvKMPMAr4X6MIMj2ULw+bH6wB65xvG3CiHpAoWzRsJ2Jce0Yfver4M8DpOsYdOcHhxkZi2Q7eXDLrimdQdLBMziCBWD+PHX7gu0pO0YqPoFTqaJwm/C+wS5TKYwsMZ9YmISw5fk/5zszIeIhZQK4/7Z20dBqBlx9PvF6ok+hvZM3bRqNX7dT5+mev3TgaG7k+4FIJFGwGv1xMP+TazNuGi/EOYFohHmScWTgeiIU29BIcyVh33zjZpMITQPm9IgxvIbSZDsb6pclDiYTFfXEGf5itkZ9LNUXek1B6YxBI/n1forYenil8+Yb+sEDT23EbSSGxMT0lBgtiLoqe4d0YTsa0Q0eFDLhTqHRpI7sxzv5y4fl7BlHohdEMw2VWoNzs0tHRE19MaR86S4e1d18QqQdkxx1333yQYfsjHqryt5S+XkM/K3vLxOARFQ6bVfGD9BUAF1VRFndKR+4AWwW2lNRNhuA=
  organization: bgrohbiel
  space: development
  on:
    repo: bengro/url-shortener